### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by ryanhca** [react-hybrid/react-hybrid#1]
I would like to propose that we look into a smooth way to integrate [Aphrodite](https://github.com/Khan/aphrodite) as an opinion on styling. We could easily adopt a "global stylesheet" (ex. material/bootstrap or build our own) and then for component specific styles use  [Aphrodite](https://github.com/Khan/aphrodite). Check out the  [docs](https://github.com/Khan/aphrodite) and let me know what you think. I have fallen in love with the framework. High level view: all component styles are written in native javascript objects inline, then; aphrodite takes these objects and creates a "style sheet" each time a component is loaded/destroyed. So you only get the styles you need for that component, you write them as if they're in line, but they're actually in line "stylesheets" so to speak.

**Comment by tannerlinsley** [comment]
Aphrodite is cool.  Are the styles for it applied as inline styles? Or are
they applied via classes?  What does the syntax look like? Does it support
the full range of css eg. media queries and animations?

I realize we could all go look these things up, but I figured we could
bring the data to us :)  Would you mind putting a link to this issue next
to the todo item in the readme?

**Comment by ryanhca** [comment]
All styles are written in line and applied to the elements via class. All the support for media queries is there as well as pseudo selectors. Last I saw they were writing child selectors into their api. But if you're writing on a component by component basis, you'll never really need child selectors. 

Syntax is as simple as writing a javascript object.

    <div className={css(styles.foobar}></div>

    const styles = StyleSheet.create({
        foobar:{
            background: "red",
            border: "1px solid blue",
            ":hover":{
                   cursor: "pointer",
                   background: "pink",
               },
              "@media(max-width: 750px)":{
                      background: "purple",
               }
        }
    })

**Comment by tannerlinsley** [comment]
Cool. This feels like it could be a really good candidate for the styling.
I've been pretty opposed to styles that are applied inline, so I love that
this does it via className. The main thing here is choosing something that
will be powerful and fast for react-hybrid, but be friendly to any other
form of customization and override (since users are going to come up with
hundreds of ways to customize their styles, I'm sure)

**Comment by tannerlinsley** [comment]
Refer to the new readme :(
